// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: mod/http/config.proto

package http

import (
	http "github.com/xtls/xray-core/transport/internet/headers/http"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Config struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Host               string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Path               string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	IdleTimeout        int32                  `protobuf:"varint,3,opt,name=idle_timeout,json=idleTimeout,proto3" json:"idle_timeout,omitempty"`
	HealthCheckTimeout int32                  `protobuf:"varint,4,opt,name=health_check_timeout,json=healthCheckTimeout,proto3" json:"health_check_timeout,omitempty"`
	Method             string                 `protobuf:"bytes,5,opt,name=method,proto3" json:"method,omitempty"`
	Header             []*http.Header         `protobuf:"bytes,6,rep,name=header,proto3" json:"header,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_mod_http_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_mod_http_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_mod_http_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Config) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Config) GetIdleTimeout() int32 {
	if x != nil {
		return x.IdleTimeout
	}
	return 0
}

func (x *Config) GetHealthCheckTimeout() int32 {
	if x != nil {
		return x.HealthCheckTimeout
	}
	return 0
}

func (x *Config) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Config) GetHeader() []*http.Header {
	if x != nil {
		return x.Header
	}
	return nil
}

var File_mod_http_config_proto protoreflect.FileDescriptor

const file_mod_http_config_proto_rawDesc = "" +
	"\n" +
	"\x15mod/http/config.proto\x12\x1cxray.transport.internet.http\x1a,transport/internet/headers/http/config.proto\"\xe3\x01\n" +
	"\x06Config\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12!\n" +
	"\fidle_timeout\x18\x03 \x01(\x05R\vidleTimeout\x120\n" +
	"\x14health_check_timeout\x18\x04 \x01(\x05R\x12healthCheckTimeout\x12\x16\n" +
	"\x06method\x18\x05 \x01(\tR\x06method\x12D\n" +
	"\x06header\x18\x06 \x03(\v2,.xray.transport.internet.headers.http.HeaderR\x06headerBg\n" +
	" com.xray.transport.internet.httpP\x01Z\"github.com/xtls/xray-core/mod/http\xaa\x02\x1cXray.Transport.Internet.Httpb\x06proto3"

var (
	file_mod_http_config_proto_rawDescOnce sync.Once
	file_mod_http_config_proto_rawDescData []byte
)

func file_mod_http_config_proto_rawDescGZIP() []byte {
	file_mod_http_config_proto_rawDescOnce.Do(func() {
		file_mod_http_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mod_http_config_proto_rawDesc), len(file_mod_http_config_proto_rawDesc)))
	})
	return file_mod_http_config_proto_rawDescData
}

var file_mod_http_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_mod_http_config_proto_goTypes = []any{
	(*Config)(nil),      // 0: xray.transport.internet.http.Config
	(*http.Header)(nil), // 1: xray.transport.internet.headers.http.Header
}
var file_mod_http_config_proto_depIdxs = []int32{
	1, // 0: xray.transport.internet.http.Config.header:type_name -> xray.transport.internet.headers.http.Header
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_mod_http_config_proto_init() }
func file_mod_http_config_proto_init() {
	if File_mod_http_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mod_http_config_proto_rawDesc), len(file_mod_http_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mod_http_config_proto_goTypes,
		DependencyIndexes: file_mod_http_config_proto_depIdxs,
		MessageInfos:      file_mod_http_config_proto_msgTypes,
	}.Build()
	File_mod_http_config_proto = out.File
	file_mod_http_config_proto_goTypes = nil
	file_mod_http_config_proto_depIdxs = nil
}
